export const NOTIFICATION_TYPES = {
  EMPLOYEE_CREATED: "EMPLOYEE_CREATED",
  EMPLOYEE_UPDATED: "EMPLOYEE_UPDATED",
  EMPLOYEE_DELETED: "EMPLOYEE_DELETED",
  LEAVE_APPLIED: "LEAVE_APPLIED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",
  ATTENDANCE_CORRECTION_REQUESTED: "ATTENDANCE_CORRECTION_REQUESTED",
  ATTENDANCE_CORRECTION_APPROVED: "ATTENDANCE_CORRECTION_APPROVED",
  ATTENDANCE_CORRECTION_REJECTED: "ATTENDANCE_CORRECTION_REJECTED",
  HOLIDAY_ADDED: "HOLIDAY_ADDED",
  ANNOUNCEMENT_PUBLISHED: "ANNOUNCEMENT_PUBLISHED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_APPROVED: "DOCUMENT_APPROVED",
  DOCUMENT_REJECTED: "DOCUMENT_REJECTED",
  REVIEW_PUBLISHED: "REVIEW_PUBLISHED",
  BIRTHDAY: "BIRTHDAY",
  WORK_ANNIVERSARY: "WORK_ANNIVERSARY",
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  SYSTEM: "SYSTEM",
} as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];
