import {
  UserPlus,
  UserCog,
  UserMinus,
  CalendarPlus,
  CalendarCheck,
  CalendarX,
  Clock,
  CheckCircle2,
  XCircle,
  CalendarHeart,
  Megaphone,
  FileUp,
  FileCheck,
  FileX,
  ClipboardCheck,
  ClipboardList,
  Eye,
  Repeat,
  Cake,
  Award,
  KeyRound,
  ShieldCheck,
  Bell,
  type LucideIcon,
} from "lucide-react";
import { NotificationType } from "@/constants/notification-types";

export const NOTIFICATION_ICON: Record<NotificationType, LucideIcon> = {
  EMPLOYEE_CREATED: UserPlus,
  EMPLOYEE_UPDATED: UserCog,
  EMPLOYEE_DELETED: UserMinus,
  LEAVE_APPLIED: CalendarPlus,
  LEAVE_APPROVED: CalendarCheck,
  LEAVE_REJECTED: CalendarX,
  ATTENDANCE_CORRECTION_REQUESTED: Clock,
  ATTENDANCE_CORRECTION_APPROVED: CheckCircle2,
  ATTENDANCE_CORRECTION_REJECTED: XCircle,
  HOLIDAY_ADDED: CalendarHeart,
  ANNOUNCEMENT_PUBLISHED: Megaphone,
  DOCUMENT_UPLOADED: FileUp,
  DOCUMENT_APPROVED: FileCheck,
  DOCUMENT_REJECTED: FileX,
  REVIEW_PUBLISHED: ClipboardCheck,
  BIRTHDAY: Cake,
  WORK_ANNIVERSARY: Award,
  TASK_ASSIGNED: ClipboardList,
  TASK_REASSIGNED: Repeat,
  TASK_SUBMITTED_FOR_REVIEW: Eye,
  PASSWORD_RESET: KeyRound,
  PASSWORD_CHANGED: ShieldCheck,
  SYSTEM: Bell,
};

export const NOTIFICATION_ICON_COLOR: Record<NotificationType, string> = {
  EMPLOYEE_CREATED: "text-blue-500",
  EMPLOYEE_UPDATED: "text-blue-500",
  EMPLOYEE_DELETED: "text-red-500",
  LEAVE_APPLIED: "text-blue-500",
  LEAVE_APPROVED: "text-emerald-500",
  LEAVE_REJECTED: "text-red-500",
  ATTENDANCE_CORRECTION_REQUESTED: "text-blue-500",
  ATTENDANCE_CORRECTION_APPROVED: "text-emerald-500",
  ATTENDANCE_CORRECTION_REJECTED: "text-red-500",
  HOLIDAY_ADDED: "text-purple-500",
  ANNOUNCEMENT_PUBLISHED: "text-amber-500",
  DOCUMENT_UPLOADED: "text-blue-500",
  DOCUMENT_APPROVED: "text-emerald-500",
  DOCUMENT_REJECTED: "text-red-500",
  REVIEW_PUBLISHED: "text-violet-500",
  BIRTHDAY: "text-pink-500",
  WORK_ANNIVERSARY: "text-amber-500",
  TASK_ASSIGNED: "text-blue-500",
  TASK_REASSIGNED: "text-violet-500",
  TASK_SUBMITTED_FOR_REVIEW: "text-amber-500",
  PASSWORD_RESET: "text-orange-500",
  PASSWORD_CHANGED: "text-orange-500",
  SYSTEM: "text-muted-foreground",
};
