export const API_ENDPOINTS = {
  HEALTH: "/health",
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    SET_PASSWORD: "/auth/set-password",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    ME: "/auth/me",
    ADMIN_RESET_PASSWORD: (userId: string) =>
      `/auth/admin/reset-password/${userId}`,
  },
  EMPLOYEES: {
    LIST: "/employees",
    CREATE: "/employees",
    ME: "/employees/me",
    ASSIGNABLE: "/employees/assignable",
    DETAIL: (id: string) => `/employees/${id}`,
    ACTIVATE: (id: string) => `/employees/${id}/activate`,
    DEACTIVATE: (id: string) => `/employees/${id}/deactivate`,
    PROMOTE_TO_PERMANENT: (id: string) => `/employees/${id}/promote-to-permanent`,
  },
  DEPARTMENTS: {
    LIST: "/departments",
    CREATE: "/departments",
    UPDATE: (id: string) => `/departments/${id}`,
    ACTIVATE: (id: string) => `/departments/${id}/activate`,
    DEACTIVATE: (id: string) => `/departments/${id}/deactivate`,
    SET_HEAD: (id: string) => `/departments/${id}/head`,
  },
  DESIGNATIONS: {
    LIST: "/designations",
    CREATE: "/designations",
    UPDATE: (id: string) => `/designations/${id}`,
    ACTIVATE: (id: string) => `/designations/${id}/activate`,
    DEACTIVATE: (id: string) => `/designations/${id}/deactivate`,
  },
  ATTENDANCE: {
    CHECK_IN: "/attendance/check-in",
    CHECK_OUT: "/attendance/check-out",
    TODAY: "/attendance/today",
    HISTORY: "/attendance/history",
    HISTORY_EXPORT: "/attendance/history/export",
    CALENDAR: "/attendance/calendar",
    SUMMARY: "/attendance/summary",
    ADMIN_LIST: "/attendance/admin",
    ADMIN_EXPORT: "/attendance/admin/export",
  },
  ATTENDANCE_CORRECTIONS: {
    CREATE: "/attendance/corrections",
    MINE: "/attendance/corrections/mine",
    ADMIN_LIST: "/attendance/corrections",
    APPROVE: (id: string) => `/attendance/corrections/${id}/approve`,
    REJECT: (id: string) => `/attendance/corrections/${id}/reject`,
  },
  LEAVES: {
    APPLY: "/leaves",
    MINE: "/leaves/me",
    BALANCE: "/leaves/balance",
    CANCEL: (id: string) => `/leaves/${id}/cancel`,
    ADMIN_LIST: "/leaves",
    APPROVE: (id: string) => `/leaves/${id}/approve`,
    REJECT: (id: string) => `/leaves/${id}/reject`,
  },
  HOLIDAYS: {
    LIST: "/holidays",
    CREATE: "/holidays",
    UPDATE: (id: string) => `/holidays/${id}`,
    ACTIVATE: (id: string) => `/holidays/${id}/activate`,
    DEACTIVATE: (id: string) => `/holidays/${id}/deactivate`,
  },
  DASHBOARD: {
    ADMIN: "/dashboard/admin",
  },
  REPORTS: {
    ATTENDANCE: "/reports/attendance",
    ATTENDANCE_EXPORT: "/reports/attendance/export",
    LEAVE: "/reports/leave",
    LEAVE_EXPORT: "/reports/leave/export",
    EMPLOYEES: "/reports/employees",
    EMPLOYEES_EXPORT: "/reports/employees/export",
    DEPARTMENTS: "/reports/departments",
    MONTHLY_SUMMARY: "/reports/monthly-summary",
    MONTHLY_SUMMARY_EXPORT: "/reports/monthly-summary/export",
    PRINT_LOG: "/reports/print-log",
  },
  SEARCH: "/search",
  NOTIFICATIONS: {
    LIST: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  ANNOUNCEMENTS: {
    LIST: "/announcements",
    RECENT: "/announcements/recent",
    ADMIN_LIST: "/announcements/admin",
    DETAIL: (id: string) => `/announcements/${id}`,
    CREATE: "/announcements",
    UPDATE: (id: string) => `/announcements/${id}`,
    PUBLISH: (id: string) => `/announcements/${id}/publish`,
    ARCHIVE: (id: string) => `/announcements/${id}/archive`,
  },
  ACTIVITY: {
    LIST: "/activity",
  },
  CONFIGURATION: {
    GET: "/configuration",
    COMPANY_PROFILE: "/configuration/company-profile",
    LOGO: "/configuration/logo",
    OFFICE_SETTINGS: "/configuration/office-settings",
    LEAVE_POLICY: "/configuration/leave-policy",
    NOTIFICATION_SETTINGS: "/configuration/notification-settings",
    EMAIL_SETTINGS: "/configuration/email-settings",
    SEND_TEST_EMAIL: "/configuration/email-settings/test-email",
    SECURITY_SETTINGS: "/configuration/security-settings",
    GENERAL_SETTINGS: "/configuration/general-settings",
  },
  PUBLIC: {
    COMPANY_BRANDING: "/public/company-branding",
    COMPANY_LOGO: "/public/company-logo",
  },
  DOCUMENTS: {
    LIST: (employeeId: string) => `/employees/${employeeId}/documents`,
    UPLOAD: (employeeId: string) => `/employees/${employeeId}/documents`,
    DOWNLOAD_URL: (documentId: string) => `/documents/${documentId}/download-url`,
    DELETE: (documentId: string) => `/documents/${documentId}`,
    RESTORE: (documentId: string) => `/documents/${documentId}/restore`,
    APPROVE: (documentId: string) => `/documents/${documentId}/approve`,
    REJECT: (documentId: string) => `/documents/${documentId}/reject`,
  },
  TASKS: {
    LIST: "/tasks",
    CREATE: "/tasks",
    MINE: "/tasks/me",
    TEAM: "/tasks/team",
    DETAIL: (taskId: string) => `/tasks/${taskId}`,
    UPDATE: (taskId: string) => `/tasks/${taskId}`,
    CANCEL: (taskId: string) => `/tasks/${taskId}`,
    STATUS: (taskId: string) => `/tasks/${taskId}/status`,
    REASSIGN: (taskId: string) => `/tasks/${taskId}/reassign`,
    COMMENTS: (taskId: string) => `/tasks/${taskId}/comments`,
    ATTACHMENTS: (taskId: string) => `/tasks/${taskId}/attachments`,
    ATTACHMENT_DOWNLOAD_URL: (attachmentId: string) =>
      `/task-attachments/${attachmentId}/download-url`,
  },
  ADOBE_LICENSES: {
    GET: "/adobe-licenses",
    UPDATE: "/adobe-licenses",
    ACCESS_ME: "/adobe-licenses/access/me",
    ACCESS_LIST: "/adobe-licenses/access",
    GRANT_ACCESS: (userId: string) => `/adobe-licenses/access/${userId}`,
    REVOKE_ACCESS: (userId: string) => `/adobe-licenses/access/${userId}`,
  },
} as const;
