export const ROUTES = {
  DASHBOARD: "/",
  ATTENDANCE: "/attendance",
  ATTENDANCE_TEAM: "/attendance/team",
  LEAVE: "/leave",
  LEAVE_ADMIN: "/leave/admin",
  EMPLOYEES: "/employees",
  EMPLOYEE_NEW: "/employees/new",
  EMPLOYEE_DETAIL: (id: string) => `/employees/${id}`,
  REPORTS: "/reports",
  REPORTS_ATTENDANCE: "/reports/attendance",
  REPORTS_LEAVE: "/reports/leave",
  REPORTS_EMPLOYEES: "/reports/employees",
  REPORTS_DEPARTMENTS: "/reports/departments",
  REPORTS_MONTHLY_SUMMARY: "/reports/monthly-summary",
  PROFILE: "/profile",
  ANNOUNCEMENTS: "/announcements",
  ANNOUNCEMENTS_ADMIN: "/announcements/admin",
  ANNOUNCEMENT_DETAIL: (id: string) => `/announcements/${id}`,
  ACTIVITY: "/activity",
  ADMINISTRATION: "/administration",
  ADMINISTRATION_COMPANY_PROFILE: "/administration/company-profile",
  ADMINISTRATION_OFFICE_SETTINGS: "/administration/office-settings",
  ADMINISTRATION_LEAVE_POLICY: "/administration/leave-policy",
  ADMINISTRATION_NOTIFICATION_SETTINGS: "/administration/notification-settings",
  ADMINISTRATION_EMAIL_SETTINGS: "/administration/email-settings",
  ADMINISTRATION_SECURITY_SETTINGS: "/administration/security-settings",
  ADMINISTRATION_GENERAL_SETTINGS: "/administration/general-settings",
  ADMINISTRATION_DEPARTMENTS: "/administration/departments",
  ADMINISTRATION_DESIGNATIONS: "/administration/designations",
  ADMINISTRATION_HOLIDAYS: "/administration/holidays",
  LOGIN: "/login",
  SET_PASSWORD: "/set-password",
} as const;
